### ISSUE TITLE
[FEAT] Home 화면 구성 요구사항

### ISSUE THREAD

**Issue by rlaekdud** [sw24-11/llmeta-fe#3]
**📌 기능 요구사항**
- [x] image, pdf 부분을 체크박스로 선택할 수 있도록 변경
- [x] Choose File 버튼에서 파일을 선택할 수 있도록 함(이때 image는 png, jpeg만 가능. 논문은 pdf 파일만 가능)
- [x] Upload file 박스 하단에 Extract 버튼 추가, 해당 버튼을 누를 시 request 요청을 백엔드로 보내도록 기능 추가
- [x] Extract response가 도착할 때까지 로딩창 추가
- [x] Extract response가 도착하면 /logs 페이지로 이동해 결과 디스플레이
- [x] 적절한 위치에 logs 페이지로 이동하는 버튼 추가 필요(extract 버튼 하단에 배치하는 것이 좋을 듯 합니다!)

**📌 추가 요구사항**
- [ ] home 화면에서 상단 다크 모드 변경 적용 안되는데, 수정 가능하다면 수정 바랍니다.
1. extract request를 보낼 때 아래 사진과 같이 dataType이 함께 전송되어야 합니다. dataType은 체크 박스에서 선택한 것을 반영해야 합니다. type은 두 가지로 IMAGE, PAPER로 나뉩니다.
<img width="709" alt="스크린샷 2024-06-01 13 09 49" src="https://github.com/sw24-11/llmeta-fe/assets/24622203/6e2defd2-72b5-4559-9978-af287e5a6e24">

**Comment by seokiis** [comment]
Extract api 제외하고 resolved
