### ISSUE TITLE
[FEAT] 회원 가입 요구사항

### ISSUE THREAD

**Issue by rlaekdud** [sw24-11/llmeta-fe#4]
**📌 기능 요구사항**
- [x] Sign Up 버튼 누를 시 sign-up api 연결 필요
- [x] Check Email 버튼을 누를 시 해당 이메일에 대해 signup/redundancyCheck api로 중복 체크 필요
- [x] password 입력 란에 적절한 placeholder 필요
- [x] 우측 상단 Sign in 버튼 -> Login으로 수정
- [x] Login 버튼 누를 시 login 페이지로 이동하도록 수정

**📌 추가 요구사항**
1. 비밀번호는 8자 이상으로 설정해야 하고, 위의 모든 정보를 채우지 않을 경우 Sign Up 버튼이 활성화되지 않아야 합니다.

**Comment by seokiis** [comment]
resolved
