### ISSUE TITLE
[FEAT] 로그 페이지 요구사항

### ISSUE THREAD

**Issue by rlaekdud** [sw24-11/llmeta-fe#5]
**📌 기능 요구사항**
- [x] logs 페이지로 이동하면서 /metadata/logs api request 전송, response를 바탕으로 logs 페이지 구성
- [x] Metadata 파트에서 key-value 매칭이 한 줄씩 나오도록 수정(기존에는 2열로 나왔는데, 1열로 나오도록 수정)
- [x] 전송한 파일에 대해서 미리보기 지원
- [x] Action 탭에 Share 버튼 삭제
- [x] Action 탭에 Download 버튼을 누르면 원본 파일(메타 데이터 추출 타겟 파일)을 다운로드 할 수 있도록 수정
- [x] 좌측 하단의 Sign In 버튼을 Logout 버튼으로 수정
- [x] Logout 버튼에 logout api 연결, 로그아웃 시 로그인 전 home 화면으로 리디렉션 되도록 설정
- [x] 우측 상단의 Upload File 버튼을 누르면 home 화면으로 리디렉션, 해당 화면에서 metadata를 지원하도록 함
- [x] 좌측 탭에 상단에서부터 스택처럼 log가 쌓이도록 구성(chatGPT UI처럼)
- [x] 상단의 LLMETA Service와 깃발 이모지 삭제(중복됨)

**📌 추가 요구사항**
(선택) 추가적인 요구사항이나 문제를 자유롭게 작성해주세요.
1. 추출된 metadata는 아래와 같은 형식으로 응답이 옵니다. 특정 key에 대해서 응답이 오지 않은 경우에는 'Not provided'라는 value로 전송됩니다. 해당 경우에는 - 표시로 비워놓으시는 게 좋을 듯 합니다.
<img width="725" alt="스크린샷 2024-06-01 13 22 41" src="https://github.com/sw24-11/llmeta-fe/assets/24622203/d76b4f23-54c3-44a9-b831-ba269be37e88">
<img width="718" alt="스크린샷 2024-06-01 13 24 28" src="https://github.com/sw24-11/llmeta-fe/assets/24622203/2de80f8d-06fa-4353-99cf-5d5709e09422">

**Comment by seokiis** [comment]
resolved
