### ISSUE TITLE
[FEAT] 추출 결과에 대한 평가 기능 요구사항

### ISSUE THREAD

**Issue by rlaekdud** [sw24-11/llmeta-fe#7]
**📌 기능 요구사항**
- [x] 로그 페이지 하단에 각 추출 결과마다 평가를 할 수 있는 버튼을 추가해주세요.
- [x] 평가 버튼을 누르면 팝업으로 평가를 입력할 수 있도록 해주세요.
1. 팝업에서 입력해야 할 정보는 다음과 같습니다. 평점(10점 만점), 피드백(string)을 입력하되 그 입력 형식(평점 입력 방식 등)은 자유롭게 결정해주세요!

**📌 추가 요구사항**
1. 아래는 평가 API의 세부사항입니다.
<img width="555" alt="스크린샷 2024-06-04 12 59 16" src="https://github.com/sw24-11/llmeta-fe/assets/24622203/8b56e6f4-7852-4458-b848-5c31f2019314">

**Comment by seokiis** [comment]
did well done
